minimum_pre_commit_version: 2.20.0
default_stages: [commit, push, manual]
default_language_version:
  python: python3.8

ci:
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        exclude: ^.*\.egg-info/
        name: End of file fixer
      - id: check-merge-conflict
        name: Check for merge conflict
      - id: check-case-conflict
        name: Check for case filename conflict
      - id: check-json
        name: Check JSON syntax
      - id: check-toml
        name: Check TOML syntax
      - id: check-yaml
        name: Check YAML syntax
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
        name: Pretty format JSON files
      - id: check-ast
        name: Python AST check
      - id: debug-statements
        name: Check for debugger statments
      - id: check-docstring-first
        name: Check docstring first
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
        name: Detect AWS credentials
      - id: detect-private-key
        name: Detect private key
      - id: forbid-new-submodules
        name: Detect new git submodules
      - id: mixed-line-ending
        name: Check mixed line ending
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods
        name: Check mock mistakes
      - id: python-use-type-annotations
        name: Enforce type annotations instead of comments
      - id: python-check-blanket-noqa
        name: Enforce specifc code for noqua annotation
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.20.0
    hooks:
      - id: validate_manifest
        name: Validate manifest
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1
    hooks:
      - id: pycln
        args: [--all]
        name: Remove unused imports (pycln)
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: [--in-place]
        name: Documentation checker (docformatter)
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0
    hooks:
      - id: autopep8
        name: Code Formatter (autopep8)
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--max-line-length=88", "--extend-ignore=N803,N806,E501,Q000,W605"]
        additional_dependencies: &flake8_deps
          - flake8-annotations==2.9.0
          - flake8-broken-line==0.5.0
          - flake8-bugbear==22.7.1
          - flake8-comprehensions==3.10.0
          - flake8-eradicate==1.3.0
          - flake8-quotes==3.3.1
          - flake8-simplify==0.19.3
          - flake8-tidy-imports==4.8.0
          - flake8-type-checking==2.1.2
          - flake8-typing-imports==1.12.0
          - flake8-use-fstring==1.4
          - pep8-naming==0.13.1
          - flake8-pie==0.16.0
        name: Code checker (flake8)
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--filter-files]
        name: Import sorting (isort)
