site_name: "YData Fabric"
repo_url: https://github.com/ydataai/ydata-sdk
repo_name: ydataai/ydata-sdk
edit_uri: ""
dev_addr: 0.0.0.0:1235
site_dir: "static/docs"
nav:
  - Welcome: 'index.md'
  - Get started with Fabric:
      - "get-started/index.md"
      - Quickstart:
          - How to create your first Dataset from a CSV file: "get-started/upload_csv.md"
          - How to create your first Relational database in Fabric's Catalog: "get-started/create_multitable_dataset.md"
          - How to create your first Synthetic Data generator: "get-started/create_syntheticdata_generator.md"
          - How to create your first Synthetic Data generator for databases: "get-started/create_database_sd_generator.md"
          - How to create your first Lab: "get-started/create_lab.md"
          - How to create your first Pipeline: "get-started/create_pipeline.md"
      - Fabric Community: "get-started/fabric_community.md"
  - Data catalog:
      - 'data_catalog/index.md'
      - Connectors:
          - 'data_catalog/connectors/index.md'
          - How to create a connector?: 'data_catalog/connectors/create_connector.md'
          - Supported connectors: 'data_catalog/connectors/supported_connections.md'
          - Use a connector in Labs: 'data_catalog/connectors/use_in_labs.md'
          - Integrations examples:
              - Snowflake: 'data_catalog/connectors/integration_snowflake.md'
      - Datasources:
          - 'data_catalog/datasources/index.md'
          - Warnings: 'data_catalog/datasources/warnings.md'
          - PII identification: 'data_catalog/datasources/pii.md'
  - SDK:
      - Overview: "sdk/index.md"
      - Installation: 'sdk/installation.md'
      - Quickstart: 'sdk/quickstart.md'
      - Components:
          - "sdk/modules/connectors.md"
      - Examples:
          - Generate Tabular Data: "sdk/examples/synthesize_tabular_data.md"
          - Generate Time-Series Data: "sdk/examples/synthesize_timeseries_data.md"
          - Generate MultiTable Data: "sdk/examples/synthesizer_multitable.md"
          - Anonymization: "sdk/examples/synthesize_with_anonymization.md"
          - Privacy Level: "sdk/examples/synthesize_with_privacy_control.md"
          - Conditional Sampling: "sdk/examples/synthesize_with_conditional_sampling.md"
      - Reference:
          - Changelog: 'sdk/reference/changelog.md'
          - API:
              - Client: 'sdk/reference/api/common/client.md'
              - Connectors:
                  - 'Connector': 'sdk/reference/api/connectors/connector.md'
              - DataSources:
                  - 'DataSource': 'sdk/reference/api/datasources/datasource.md'
                  - 'Metadata': 'sdk/reference/api/datasources/metadata.md'
              - Synthesizers:
                  - Synthesizer: 'sdk/reference/api/synthesizers/base.md'
                  - Regular: 'sdk/reference/api/synthesizers/regular.md'
                  - TimeSeries: 'sdk/reference/api/synthesizers/timeseries.md'
                  - MultiTable: 'sdk/reference/api/synthesizers/multitable.md'
              - Types: 'sdk/reference/api/common/types.md'


theme:
  name: material
  language: en
  palette:
    - scheme: ydata
      media: "(prefers-color-scheme: light)"
      primary: custom
  logo: 'https://assets.ydata.ai/logo_notext_nbg.png'
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - header.autohide
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - toc.integrate
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - def_list
  - meta
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - tables
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  version:
    provider: mike
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ydataai
watch:
  - src
plugins:
  - search:
        lang: en
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            filters: ["!^_", "!^__"]
          import:
          - https://docs.python.org/3/objects.inv
          - http://pandas.pydata.org/pandas-docs/stable/objects.inv
          setup_commands:
            - import sys
            - sys.path.append('.src')
          merge_init_into_class: yes
          show_submodules: no
