site_name: "YData Fabric"
repo_url: https://github.com/ydataai/ydata-sdk
repo_name: ydataai/ydata-sdk
edit_uri: ""
dev_addr: 0.0.0.0:1235
site_dir: "static/docs"
nav:
  - Welcome: 'index.md'
  - Get started with Fabric: "get-started/fabric_community.md"
  - Data Catalog:
      - "data_catalog/index.md"
      - Connectors:
        - "data_catalog/connectors/index.md"
        - Supported connections:
          - "data_catalog/connectors/supported_connections.md"
          - File formats: "data_catalog/connectors/file_formats.md"
        - Use in Labs: "data_catalog/connectors/use_in_labs.md"
      - Datasets:
        - "data_catalog/datasets/index.md"
        - Dataset overview:
          - "data_catalog/datasets/dataset_overview.md"
          - Warnings: "data_catalog/datasets/warnings.md"
        - Dataset Profiling: "data_catalog/datasets/profiling.md"
        - Dataset Metadata: "data_catalog/datasets/metadata.md"
        - Automated PII identification: "data_catalog/datasets/pii.md"
        - Explore in Labs: "data_catalog/datasets/explore_in_labs.md"
  - SDK:
      - Overview: "sdk/index.md"
      - Installation: 'sdk/installation.md'
      - Quickstart: 'sdk/quickstart.md'
      - Components:
          - "sdk/modules/connectors.md"
      - Examples:
        - Generate Tabular Data: "examples/synthesize_tabular_data.md"
        - Generate Time-Series Data: "examples/synthesize_timeseries_data.md"
        - Anonymization: "examples/synthesize_with_anonymization.md"
        - Privacy Level: "examples/synthesize_with_privacy_control.md"
        - Conditional Sampling: "examples/synthesize_with_conditional_sampling.md"
      - Reference:
          - Changelog: 'sdk/reference/changelog.md'
          - API:
              - Client: 'reference/api/common/client.md'
              - Connectors:
                  - 'Connector': 'reference/api/connectors/connector.md'
              - DataSources:
                  - 'DataSource': 'reference/api/datasources/datasource.md'
                  - 'Metadata': 'reference/api/datasources/metadata.md'
              - Synthesizers:
                  - Synthesizer: 'reference/api/synthesizers/base.md'
                  - Regular: 'reference/api/synthesizers/regular.md'
                  - TimeSeries: 'reference/api/synthesizers/timeseries.md'
              - Types: 'reference/api/common/types.md'

theme:
  name: material
  language: en
  font: 'Roboto'
  palette:
    - scheme: ydata
      media: "(prefers-color-scheme: light)"
      primary: custom
  logo: 'https://assets.ydata.ai/logo_notext_nbg.png'
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - header.autohide
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - toc.integrate
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - def_list
  - meta
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - tables
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  version:
    provider: mike
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ydataai
watch:
  - src
plugins:
  - search:
        lang: en
  - autorefs
  - mkdocstrings:
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          selection:
            filters: ["!^_", "!^__"]
          import:
          - https://docs.python.org/3/objects.inv
          - http://pandas.pydata.org/pandas-docs/stable/objects.inv
          setup_commands:
            - import sys
            - sys.path.append('.src')
          merge_init_into_class: yes
          show_submodules: no
