name: Release



on:
  release:
    types:
      - released



jobs:
  package:
    name: Build and Package
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Version
      id: version
      run: echo "value=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - uses: actions/cache@v3
      name: Cache pip dependencies
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install-dev

    # - name: Lint
    #   run: make lint

    - name:  Build package
      run: make package version=${{ steps.version.outputs.value }}

    - name: Upload Pipeline Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-artifacts
        path: dist/


  upload-assets:
    name: Upload Assets to Release
    runs-on: ubuntu-22.04

    needs: package

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: built-artifacts
        path: dist/

    - uses: AButler/upload-release-assets@v2.0
      with:
        files: "dist/*"
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        release-tag: ${{ needs.package.outputs.version }}


  publish-pypi:
    name: Publish packages to PyPi
    runs-on: ubuntu-22.04

    needs: package

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: built-artifacts
        path: dist/

    - uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
